# Hardcoding stuff for Shiny App

labels <- data.frame(codename = c("Name",
                                "Art",
                                "Wasser_min_Sommer",
                                "Wasser_max_Sommer",
                                "Wasser_min_Winter",
                                "Wasser_max_Winter",
                                "Duengen_Sommer",
                                "Duengen_Winter"),
                     labels = c("Name",
                                "Art",
                                "Min. Gießen (Sommer)",
                                "Max. Gießen (Sommer)",
                                "Min. Gießen (Winter)",
                                "Max. Gießen (Winter)",
                                "Düngen (Sommer)",
                                "Düngen (Winter)"),
                     sowi = c("sowi",
                              "sowi",
                              "so",
                              "so",
                              "wi",
                              "wi",
                              "so", 
                              "wi"))
